// paper-share-angular/src/app/search-dialog/search-dialog.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-search-dialog',
  templateUrl: './search-dialog.component.html',
  styleUrls: ['./search-dialog.component.css']
})
export class SearchDialogComponent implements OnInit {

  constructor() { }
  dialog = false;
  ngOnInit(): void {
  }

  openDialogue() {
    this.dialog = true;
  }
  closeQuestionDialog() {
    this.dialog = false;

  }
  search() {

  }

}

<div>
    <button (click)="openDialogue()">Search</button>
        <div *ngIf="dialog">
                <mat-dialog-content max-width="600px">
                    <mat-card>
                        <mat-card-title>
                            <span class="headline">Search and Filter</span>
                        </mat-card-title>
                        <mat-card-content>
                            <mat-grid-list cols="2" rowHeight="50px">
                                <mat-grid-tile [colspan]="2" [rowspan]="1">
                                    <input type="text" placeholder="Title*">
                                </mat-grid-tile>
                               <mat-grid-tile [colspan]="2" [rowspan]="1">
                                    <input type="text" placeholder="Authors*">
                                </mat-grid-tile>
                                <mat-grid-tile [colspan]="1" [rowspan]="1">
                                    <input type="text" placeholder="Subject*">
                                </mat-grid-tile>
                                <mat-grid-tile [colspan]="1" [rowspan]="1">
                                    <input type="text" placeholder="Language*">
                                </mat-grid-tile>
                                 <mat-grid-tile [colspan]="2" [rowspan]="1">
                                    <input type="date" name="" id="" placeholder="dd-MM-yyyy">
                                </mat-grid-tile>
                                <mat-grid-tile [colspan]="2" [rowspan]="1">
                                    <input type="text" placeholder="Keywords">
                                </mat-grid-tile>
                                <mat-grid-tile [colspan]="2" [rowspan]="1">
                                    <textarea placeholder="Text*"></textarea>
                                </mat-grid-tile>
                            </mat-grid-list>
                        </mat-card-content>
                    </mat-card>
            
                </mat-dialog-content>
                <mat-dialog-actions>
                    <button mat-button (click)="closeQuestionDialog()">Close</button>
                    <button mat-button (click)="search()">Apply</button>
                </mat-dialog-actions>
            </div>
</div>

// paper_share_vue/src/components/searchDialog.vue
<template>
    <div>

    <v-dialog v-model="dialog" persistent max-width="600px">
                    <template v-slot:activator="{ on }">
                        <v-btn large color="blue-grey lighten-3"  v-on="on" class="" style="">
                            Search
                            <v-icon right dark>search</v-icon>
                        </v-btn>
                    </template>
                    <v-card>
                    <v-card-title>
                        <span class="headline">Search and Filter</span>
                    </v-card-title>
                    <v-card-text>
                        <v-container>
                            
                            <v-row>
                                <v-text-field v-model="title" shaped outlined label="Title*" required></v-text-field>
                                </v-row>
                                <v-row >
                                    <v-text-field v-model="authors" shaped outlined label="Authors*" required></v-text-field>
                                </v-row>
                                <v-row>
                                    <v-col cols="12" sm="6">
                                        <v-combobox v-model="subject"
                                            label="Subject*"
                                        ></v-combobox>
                                    </v-col>
                                    <v-col cols="12" sm="6" v-model="language">
                                        <v-combobox
                                            label="Language*"
                                        ></v-combobox>
                                    </v-col>
                                </v-row>
                                <v-row >
                                    <v-text-field type="date" v-model="date"></v-text-field>
                                </v-row>
                                <v-row>
                                    <v-text-field v-model="keywords" shaped outlined label="Keywords*" required></v-text-field>
                                </v-row>
                                <v-row>
                                    <v-textarea v-model="text" shaped outlined label="Text*" required></v-textarea>
                                </v-row>
                                    
                               
                        </v-container>
                    </v-card-text>
                    <v-card-actions class="justify-center">
                        <v-btn @click="closeQuestionDialog()" outlined color="indigo"  >Close</v-btn>
                        <v-btn @click="search()" color="indigo"  >Apply</v-btn>
                    </v-card-actions>
                </v-card>
    </v-dialog>
    </div>
</template>

<script>
  export default {
        name: "searchDialog",
        data(){
        return {
            dialog: false,
            authors: "",
            title: "",
            language: "",
            subject: "",
            date: "",
            keywords: "",
            text: ""
            }  
        },
        methods: {
            closeQuestionDialog:function(){
                this.dialog = false;
            },
        }
  }
</script>

<style>
</style>
